# Generated by Django 3.0.5 on 2020-05-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_main_name', models.CharField(help_text='Provide main institution name.', max_length=255)),
                ('inst_sub_name', models.CharField(blank=True, help_text='Provide name of department, division, etc., responsible for artist files collections.', max_length=255)),
                ('inst_website', models.URLField(help_text='Provide website address related to main institution or department, division, etc., for example, "www.cartermuseum.org/library."', max_length=255)),
                ('inst_email', models.EmailField(help_text='Provide best email for answering questions about artist files collections. Prefer general email such as "library@cartermuseum.org"', max_length=255)),
                ('inst_tel', models.CharField(help_text='Provide best telephone contact for answering questions about artist files collections.', max_length=50)),
                ('inst_date_created', models.DateField(auto_now_add=True)),
                ('inst_date_saved', models.DateField(auto_now=True)),
                ('inst_collection', models.ForeignKey(help_text='Create an artist files collection and provide details. Multiple collections allowed and encouraged. Create a separate entry for each formally named collection or collection with special characteristics, for example "The Nettie Wheeler Artist Files on Native American Artists."', on_delete=django.db.models.deletion.CASCADE, to='collections_app.Collection')),
                ('inst_type', models.ManyToManyField(default='', help_text='Choose all types that are relevant. Create a new type if there is not a fit.', related_name='Institution', to='institutions_app.InstitutionType')),
            ],
            options={
                'ordering': ['inst_main_name'],
            },
        ),
    ]
