# Generated by Django 3.0.5 on 2020-05-08 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections_app', '0020_auto_20200508_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('definition', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_main_name', models.CharField(max_length=255)),
                ('inst_sub_name', models.CharField(blank=True, max_length=255)),
                ('inst_email', models.EmailField(max_length=255)),
                ('inst_tel', models.CharField(max_length=50)),
                ('inst_website', models.URLField(max_length=255)),
                ('inst_date_created', models.DateField(auto_now_add=True)),
                ('inst_date_saved', models.DateField(auto_now=True)),
                ('inst_coll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections_app.Collection')),
                ('inst_type', models.ManyToManyField(default='', related_name='Institution', to='institutions_app.InstitutionType')),
            ],
            options={
                'ordering': ['inst_main_name'],
            },
        ),
    ]
