# Generated by Django 3.0.5 on 2020-05-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='inst_coll',
        ),
    ]
