# Generated by Django 3.0.5 on 2020-05-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_tel',
            field=models.CharField(help_text='Provide best telephone contact for answering questions about artist files.', max_length=50),
        ),
    ]
