# Generated by Django 3.0.5 on 2020-05-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0002_auto_20200512_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_email',
            field=models.EmailField(help_text='Provide best email for answering questions about artist files. Prefer general email such as "library@cartermuseum.org"', max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_sub_name',
            field=models.CharField(blank=True, help_text='Provide name of department, division, etc., responsible for artist files.', max_length=255),
        ),
    ]
