# Generated by Django 3.0.5 on 2020-05-09 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0022_auto_20200508_2344'),
        ('institutions_app', '0003_institution_inst_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_collection',
            field=models.ForeignKey(default='Add a collection', on_delete=django.db.models.deletion.CASCADE, to='collections_app.Collection'),
        ),
    ]
