# Generated by Django 3.0.5 on 2020-05-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0013_auto_20200513_1501'),
        ('institutions_app', '0004_auto_20200512_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_collection',
            field=models.ForeignKey(help_text='Create an artist files collection and provide details. Use "General Collection" if describing all files as one combined entry. Create a separate entry for each formally named collection or collection with special characteristics, for example "The Nettie Wheeler Artist Files on Native American Artists." Multiple collections allowed and encouraged.', on_delete=django.db.models.deletion.CASCADE, to='collections_app.Collection', verbose_name='Add Collection(s)'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_email',
            field=models.EmailField(help_text='Provide best email for answering questions about artist files. Prefer general email such as "library@cartermuseum.org"', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_main_name',
            field=models.CharField(help_text='Provide main institution name.', max_length=255, verbose_name='Main Name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_sub_name',
            field=models.CharField(blank=True, help_text='Provide name of department, division, etc., responsible for artist files.', max_length=255, verbose_name='Main Name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_tel',
            field=models.CharField(help_text='Provide best telephone contact for answering questions about artist files.', max_length=50, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_type',
            field=models.ManyToManyField(default='', help_text='Choose all types that are relevant. Create a new type if there is not a fit.', related_name='Institution', to='institutions_app.InstitutionType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_website',
            field=models.URLField(help_text='Provide website address related to main institution or department, division, etc., for example, "www.cartermuseum.org/library."', max_length=255, verbose_name='Website'),
        ),
    ]
