# Generated by Django 3.0.5 on 2020-05-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0005_auto_20200509_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_email',
            field=models.EmailField(help_text='Provide email best for answering questions about artist files collections.', max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_main_name',
            field=models.CharField(help_text='Provide main institution name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_sub_name',
            field=models.CharField(blank=True, help_text='Provide name of institutional department responsbiel for artist files collections.', max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_tel',
            field=models.CharField(help_text='Provide telephone best for answering questions about artist files collections.', max_length=50),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_type',
            field=models.ManyToManyField(default='', help_text='Choose institution type.', related_name='Institution', to='institutions_app.InstitutionType'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_website',
            field=models.URLField(help_text='Use website best related to artist files collections.', max_length=255),
        ),
    ]
