# Generated by Django 3.0.5 on 2020-05-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0006_auto_20200509_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_sub_name',
            field=models.CharField(blank=True, help_text='Provide name of department, division, etc., responsible for artist files collections.', max_length=255),
        ),
    ]
