# Generated by Django 3.0.5 on 2020-05-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0007_auto_20200509_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_email',
            field=models.EmailField(help_text='Provide best email for answering questions about artist files collections.', max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_tel',
            field=models.CharField(help_text='Provide best telephone contact for answering questions about artist files collections.', max_length=50),
        ),
    ]
