# Generated by Django 3.0.5 on 2020-05-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0013_auto_20200513_1501'),
        ('institutions_app', '0007_auto_20200513_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_collection',
            field=models.ForeignKey(help_text='Create an artist files collection and provide details. Use "General Collection" if describing all files as one combined entry. Create a separate entry for each formally named collection or collection with special characteristics, for example "The Nettie Wheeler Artist Files on Native American Artists." Multiple collections allowed and encouraged.', on_delete=django.db.models.deletion.CASCADE, to='collections_app.Collection', verbose_name='Collection(s)'),
        ),
    ]
