# Generated by Django 3.0.5 on 2020-05-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0013_auto_20200513_1501'),
        ('institutions_app', '0008_auto_20200513_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_collection',
            field=models.ForeignKey(help_text='Create an artist files collection and provide details. Use "General Collection" if describing all files as one combined entry. Create a separate entry for each formally named collection or collection with special characteristics, for example "The Nettie Wheeler Artist Files on Native American Artists." Multiple collections allowed and encouraged.', on_delete=django.db.models.deletion.CASCADE, to='collections_app.Collection', verbose_name='Collections'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_type',
            field=models.ManyToManyField(default='', help_text='Choose all types that are relevant. Create a new type if there is not a fit.', related_name='Institution', to='institutions_app.InstitutionType', verbose_name='Typ'),
        ),
    ]
