# Generated by Django 3.0.5 on 2020-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0009_auto_20200509_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_website',
            field=models.URLField(help_text='Provide website address related to main institution or department, division, etc., for example, "www.cartermuseum.org/library."', max_length=255),
        ),
    ]
