# Generated by Django 3.0.5 on 2020-05-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0023_auto_20200509_0012'),
        ('institutions_app', '0010_auto_20200509_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_collection',
            field=models.ForeignKey(help_text='Add details about an artist files collection. Multiple collections allowed and encouraged.', on_delete=django.db.models.deletion.CASCADE, to='collections_app.Collection'),
        ),
    ]
