# Generated by Django 3.0.5 on 2020-05-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0010_auto_20200513_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['inst_main_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='institutiontype',
            options={'ordering': ['type_name'], 'verbose_name': 'Person Type', 'verbose_name_plural': 'Person Types'},
        ),
    ]
