# Generated by Django 3.0.5 on 2020-05-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0013_auto_20200518_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiontype',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
