# Generated by Django 3.0.5 on 2020-05-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0013_auto_20200509_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='inst_email',
            field=models.EmailField(help_text='Provide best email for answering questions about artist files collections. Prefer general email such as "library@cartermuseum.org"', max_length=255),
        ),
    ]
