# Generated by Django 3.0.5 on 2020-05-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0014_auto_20200518_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['main_name'], 'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='inst_collection',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='inst_date_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='inst_date_saved',
            new_name='date_saved',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='inst_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='inst_main_name',
            new_name='main_name',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='inst_sub_name',
            new_name='sub_name',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='inst_tel',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='inst_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='inst_website',
            new_name='website',
        ),
    ]
