# Generated by Django 3.0.5 on 2020-05-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0004_auto_20200528_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='person_type',
            field=models.ManyToManyField(blank=True, help_text='If a collector, choose all types that are relevant. Create new type if there is not a fit.', related_name='Collector', to='collectors_app.PersonType', verbose_name='Person Types'),
        ),
    ]
