# Generated by Django 3.0.5 on 2020-06-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0005_auto_20200528_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collector',
            options={'ordering': ['inst_main_name'], 'verbose_name': 'Collector', 'verbose_name_plural': '** Collectors'},
        ),
    ]
