# Generated by Django 3.0.5 on 2020-06-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0006_auto_20200601_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='email_pref',
            field=models.BooleanField(blank=True, default=False, help_text='Is this the best method of contact?', verbose_name='Email Best'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collector',
            name='email',
            field=models.EmailField(help_text='Provide best email for answering questions about artist files. If an institution, prefer general email such as "library@cartermuseum.org."', max_length=255, verbose_name='Email'),
        ),
    ]
