# Generated by Django 3.0.5 on 2020-06-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0007_auto_20200601_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='email_pref',
            field=models.BooleanField(blank=True, help_text='Is this the preferred method of contact?', verbose_name='Preferred Contact'),
        ),
    ]
