# Generated by Django 3.0.5 on 2020-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0008_auto_20200601_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='telephone_pref',
            field=models.BooleanField(blank=True, default=False, help_text='Is telephone the preferred method of contact?', verbose_name='Preferred Contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collector',
            name='email_pref',
            field=models.BooleanField(blank=True, help_text='Is email the preferred method of contact?', verbose_name='Preferred Contact'),
        ),
    ]
