# Generated by Django 3.0.5 on 2020-06-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0010_auto_20200601_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='email_pref',
            field=models.BooleanField(blank=True, help_text='Is email a preferred method of contact?', verbose_name='Preferred Contact'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='telephone_pref',
            field=models.BooleanField(blank=True, help_text='Is a telephone call a preferred method of contact?', verbose_name='Preferred Contact'),
        ),
    ]
