# Generated by Django 3.0.5 on 2020-06-01 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0011_auto_20200601_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='instagram_pref',
            field=models.BooleanField(blank=True, default=False, help_text='Is Instagram a preferred method of contact?', verbose_name='Preferred Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collector',
            name='other_contact',
            field=models.CharField(default=django.utils.timezone.now, help_text='Provide other form of contact.', max_length=255, verbose_name='Other Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collector',
            name='twitter_pref',
            field=models.BooleanField(blank=True, default=False, help_text='Is a Twitter a preferred method of contact?', verbose_name='Preferred Contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collector',
            name='website',
            field=models.URLField(blank=True, help_text='Provide website address related to institution or personal collector responsible for artist files collection, for example, "www.cartermuseum.org/library"', max_length=255, verbose_name='Website'),
        ),
    ]
