# Generated by Django 3.0.5 on 2020-06-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0013_auto_20200601_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='email_pref',
            field=models.BooleanField(blank=True, verbose_name='Is email a preferred contact?'),
        ),
    ]
