# Generated by Django 3.0.5 on 2020-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0014_auto_20200601_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='instagram_pref',
            field=models.BooleanField(blank=True, verbose_name='Is Instragram a preferred contact?'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='telephone_pref',
            field=models.BooleanField(blank=True, verbose_name='Is email a preferred contact?'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='twitter_pref',
            field=models.BooleanField(blank=True, verbose_name='Is Twitter a preferred contact?'),
        ),
    ]
