# Generated by Django 3.0.5 on 2020-06-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0015_auto_20200601_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='other_pref',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is other a preferred contact?'),
            preserve_default=False,
        ),
    ]
