# Generated by Django 3.0.5 on 2020-06-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0017_auto_20200601_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='collector_bool',
            field=models.BooleanField(default=False, verbose_name='Is this the name of a private collector?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collector',
            name='person_type',
            field=models.ManyToManyField(blank=True, help_text='If a private collector, choose all types that are relevant. Create new type if there is not a fit.', related_name='Collector', to='collectors_app.PersonType', verbose_name='Person Types'),
        ),
    ]
