# Generated by Django 3.0.5 on 2020-06-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0019_auto_20200601_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='person_type',
            field=models.ManyToManyField(blank=True, help_text='If a private collector, choose all types that are relevant. Create new type if there is not a fit.', related_name='Collector', to='collectors_app.PersonType', verbose_name='Private Collector Person Types'),
        ),
    ]
