# Generated by Django 3.0.5 on 2020-06-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0022_auto_20200601_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='website_pref',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is website a preferred contact?'),
            preserve_default=False,
        ),
    ]
