# Generated by Django 3.0.5 on 2020-06-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0023_collector_website_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='instagram_pref',
            field=models.BooleanField(blank=True, verbose_name='Is Instagram a preferred contact?'),
        ),
    ]
