# Generated by Django 3.0.5 on 2020-06-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0024_auto_20200601_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='collector_bool',
        ),
        migrations.AlterField(
            model_name='collector',
            name='person_first_name',
            field=models.CharField(blank=True, help_text='Provide first name of private collector.', max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='person_last_name',
            field=models.CharField(blank=True, help_text='Provide last name of private collector.filling out this form.', max_length=255, verbose_name='Last Name'),
        ),
    ]
