# Generated by Django 3.0.5 on 2020-06-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0025_auto_20200603_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='person_last_name',
            field=models.CharField(blank=True, help_text='Provide last name of private collector.', max_length=255, verbose_name='Last Name'),
        ),
    ]
