# Generated by Django 3.0.5 on 2020-06-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0027_auto_20200605_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='inst_dealer',
        ),
    ]
