# Generated by Django 3.0.5 on 2020-06-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0030_auto_20200605_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Notes'),
        ),
    ]
