# Generated by Django 3.0.5 on 2020-06-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0037_auto_20200615_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='inst_sub2_name',
            field=models.CharField(blank=True, help_text='If an institutional collection, provide name of department, division, etc., responsible for artist files.', max_length=255, verbose_name='Institution Tertiary Name'),
        ),
        migrations.AddField(
            model_name='collector',
            name='sort_name',
            field=models.CharField(default='', help_text='Use this field to control how you want your entry to sort in a list, drop initial articles, etc.', max_length=255, verbose_name='Collector Sort Name'),
        ),
    ]
