# Generated by Django 3.0.5 on 2020-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0038_auto_20200623_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='sort_name',
            field=models.CharField(default='', help_text='Use this field to tell the system how you want your entry to be sorted in a list. You will wan to drop initial articles, etc.', max_length=255, verbose_name='Collector Sort Name'),
        ),
    ]
