# Generated by Django 3.0.5 on 2020-07-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0040_auto_20200630_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='inst_main_name',
            field=models.CharField(blank=True, help_text='If an institutional collector, provide main institution name. If consortium or collaboration, suppy official name or generalized name (use notes field to provide details). If a dealer, provide business name.', max_length=255, verbose_name='Institution Main Name'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='inst_sub2_name',
            field=models.CharField(blank=True, help_text='If an institutional collector, provide a tertiary name of department, division, etc., responsible for artist files.', max_length=255, verbose_name='Institution Tertiary Name'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='inst_sub_name',
            field=models.CharField(blank=True, help_text='If an institutional collector, provide name of department, division, etc., responsible for artist files.', max_length=255, verbose_name='Institution Secondary Name'),
        ),
    ]
