# Generated by Django 3.0.5 on 2020-07-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0043_collector_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='other_pref',
            field=models.BooleanField(blank=True, verbose_name='Is this a preferred contact?'),
        ),
    ]
