# Generated by Django 3.0.5 on 2020-07-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0045_auto_20200710_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='inst_type',
            field=models.ManyToManyField(blank=True, help_text='Choose all types that are relevant. Hold down Control or Command to select more than one field. <br />This is a shared field. Load <a href="/collectors/institution_types/" target="_blank">field page</a> to add or edit fields, then refresh this page to use.', related_name='Collector', to='collectors_app.InstitutionType', verbose_name='Institution Types'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='person_type',
            field=models.ManyToManyField(blank=True, help_text='If a private collector, choose all types that are relevant. Hold down Control or Command to select more than one field.<br />This is a shared field. Load <a href="/collectors/person_types/" target="_blank">field page</a> to add or edit fields, then refresh this page to use.', related_name='Collector', to='collectors_app.PersonType', verbose_name='Private Collector Types'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='sort_name',
            field=models.CharField(default='', help_text='Use this field to tell the system how you want your entry to be sorted in a list, dropping initial articles, etc.', max_length=255, verbose_name='Collector Sort Name'),
        ),
    ]
