# Generated by Django 3.0.5 on 2020-07-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0046_auto_20200715_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='person_type',
            field=models.ManyToManyField(blank=True, help_text='If a private collector, choose all types that are relevant. Dealers: please choose "Dealer." Hold down Control or Command to select more than one field.<br />This is a shared field. Load <a href="/collectors/person_types/" target="_blank">field page</a> to add or edit fields, then refresh this page to use.', related_name='Collector', to='collectors_app.PersonType', verbose_name='Private Collector Types'),
        ),
    ]
