# Generated by Django 3.0.5 on 2020-07-13 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0009_add_subregion'),
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='state_province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region'),
            preserve_default=False,
        ),
    ]
