# Generated by Django 3.0.5 on 2020-06-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0002_auto_20200618_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionimage',
            old_name='caption',
            new_name='image_caption',
        ),
    ]
