# Generated by Django 3.0.5 on 2020-07-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0009_add_subregion'),
        ('collections_app', '0002_auto_20200713_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='state_province',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region'),
        ),
    ]
