# Generated by Django 3.0.5 on 2020-05-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0002_auto_20200507_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_provenance',
            field=models.TextField(blank=True, help_text='Describe the ownership history of the collection', max_length=1000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_size',
            field=models.TextField(blank=True, help_text='Use to describe the size of collection, expected growth, etc.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_city',
            field=models.ManyToManyField(blank=True, help_text='Add cities that are subject focuses of the files', related_name='Collection', to='collections_app.CollectionSubjectCity'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_country',
            field=models.ManyToManyField(blank=True, help_text='Add countries that are subject focuses of the files', related_name='Collection', to='collections_app.CollectionSubjectCountry'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_county',
            field=models.ManyToManyField(blank=True, help_text='Add counties that are subject focuses of the files', related_name='Collection', to='collections_app.CollectionSubjectCounty'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_geo_area',
            field=models.ManyToManyField(blank=True, help_text='Add geographic areas, such as West U.S. that are subject focuses of the files', related_name='Collection', to='collections_app.CollectionSubjectGeoArea'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_state_prov',
            field=models.ManyToManyField(blank=True, help_text='Add states or provinces that are subject focuses of the files', related_name='Collection', to='collections_app.CollectionSubjectStateProv'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_topic',
            field=models.ManyToManyField(blank=True, help_text='Add topical terms that are the subject focuses of the files', related_name='Collection', to='collections_app.CollectionSubjectTopic'),
        ),
    ]
