# Generated by Django 3.0.5 on 2020-06-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0003_auto_20200618_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='collection',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='collections_app.Collection', verbose_name='Related Collection'),
        ),
    ]
