# Generated by Django 3.0.5 on 2020-07-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0046_auto_20200715_2137'),
        ('collections_app', '0003_auto_20200714_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionimage',
            options={'ordering': ['caption'], 'verbose_name': 'Collection Image', 'verbose_name_plural': 'Collection Images'},
        ),
        migrations.RemoveField(
            model_name='collectionimage',
            name='image_caption',
        ),
        migrations.AddField(
            model_name='collectionimage',
            name='caption',
            field=models.CharField(default='', help_text='Provide a short yet descriptive caption describing the image. 50 character limit.', max_length=50, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collector',
            field=models.ManyToManyField(help_text='Choose a collector or collectors responsible for the artist files collection. A collection can have multiple owners, for example, in the case of consortial or collaborative digital projects. Hold down “Control” or “Command” to select more than one field.', related_name='collections', to='collectors_app.Collector', verbose_name='Collector(s)'),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='image',
            field=models.ImageField(help_text='Upload image showing example material from files and/or storage systems in use.<br />Only five random images show in your collection detail view. Show us the fun stuff!', upload_to='collection/images/', verbose_name='Image File'),
        ),
    ]
