# Generated by Django 3.0.5 on 2020-05-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0003_auto_20200528_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='sub_country_url',
            field=models.URLField(blank=True, help_text='Provide URI to term.', max_length=255, verbose_name='Term Reference'),
        ),
    ]
