# Generated by Django 3.0.5 on 2020-05-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0003_auto_20200507_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_name',
            field=models.ManyToManyField(blank=True, help_text='Use for personal and institutional names that are subjects of the collection', related_name='Collection', to='collections_app.CollectionSubjectName'),
        ),
    ]
