# Generated by Django 3.0.5 on 2020-05-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0004_auto_20200528_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(default='General Artist Files Collection', help_text='Use "General Artist Files Collection" if describing all files as one combined entry; otherwise, create a separate entry for each formally named collection or collection with special characteristics, for example "The Nettie Wheeler Artist Files on Native American Artists."', max_length=255, verbose_name='Name'),
        ),
    ]
