# Generated by Django 3.0.5 on 2020-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0004_auto_20200507_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_access',
            field=models.TextField(help_text='Add policies and procedures relating to how researchers access and use the collection.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_cat_system',
            field=models.ManyToManyField(help_text='Add systems used for cataloging artist files collection.', related_name='Collection', to='collections_app.CollectionCatSystem'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_dig_access',
            field=models.URLField(blank=True, help_text='Provide URL for accessizxng digital collection.', max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_dig_projects',
            field=models.TextField(blank=True, help_text='Describe digital projects, either completed or planned.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_images',
            field=models.ImageField(blank=True, help_text='Upload images showing storage systems and/or example material from files.', upload_to='collection/images/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_name',
            field=models.CharField(blank=True, help_text='Use for formal name of a collection or to describe a collection with special characteristics, for example The Nettie Wheeler Artist Files on Native American Artists.', max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_services',
            field=models.ManyToManyField(help_text='Add reference services offered.', related_name='Collection', to='collections_app.CollectionService'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_country',
            field=models.ManyToManyField(blank=True, help_text='Add countries that are subject focuses of the files.', related_name='Collection', to='collections_app.CollectionSubjectCountry'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_county',
            field=models.ManyToManyField(blank=True, help_text='Add counties that are subject focuses of the files.', related_name='Collection', to='collections_app.CollectionSubjectCounty'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_geo_area',
            field=models.ManyToManyField(blank=True, help_text='Add geographic areas, such as West U.S. that are subject focuses of the files.', related_name='Collection', to='collections_app.CollectionSubjectGeoArea'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_name',
            field=models.ManyToManyField(blank=True, help_text='Add personal and institutional names that are subjects of the collection.', related_name='Collection', to='collections_app.CollectionSubjectName'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_state_prov',
            field=models.ManyToManyField(blank=True, help_text='Add states or provinces that are subject focuses of the files.', related_name='Collection', to='collections_app.CollectionSubjectStateProv'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_topic',
            field=models.ManyToManyField(blank=True, help_text='Add topical terms that are the subject focuses of the files.', related_name='Collection', to='collections_app.CollectionSubjectTopic'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_website',
            field=models.URLField(blank=True, help_text='Add website describing or providing access to the collection.', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcounty',
            name='coll_sub_county',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcounty',
            name='coll_sub_county_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionsubjectname',
            name='coll_sub_name',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='collectionsubjectname',
            name='coll_sub_name_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionsubjectstateprov',
            name='coll_sub_state_prov',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='collectionsubjectstateprov',
            name='coll_sub_state_prov_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255),
        ),
    ]
