# Generated by Django 3.0.5 on 2020-07-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('collections_app', '0004_auto_20200715_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='state_province',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region', verbose_name='State or Province'),
        ),
    ]
