# Generated by Django 3.0.5 on 2020-06-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0037_auto_20200615_2243'),
        ('collections_app', '0005_auto_20200618_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collector',
            field=models.ManyToManyField(help_text='Create or choose a collector responsible for the artist files collection. A collection can have multiple owners, for example, in the case of consortial or collaborative digital projects.', related_name='collections', to='collectors_app.Collector', verbose_name='Collector(s)'),
        ),
    ]
