# Generated by Django 3.0.5 on 2020-05-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0005_auto_20200507_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_dig_access',
            field=models.URLField(blank=True, help_text='Provide URL for accessing digital collection.', max_length=255),
        ),
    ]
