# Generated by Django 3.0.5 on 2020-05-07 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0006_auto_20200507_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='coll_provenance',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='coll_size',
        ),
        migrations.AddField(
            model_name='collection',
            name='coll_description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Provide a general description of the collection, including history, provenance, and size.', max_length=1000),
            preserve_default=False,
        ),
    ]
