# Generated by Django 3.0.5 on 2020-06-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0006_auto_20200618_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='image_caption',
            field=models.CharField(default='', max_length=50, verbose_name='Image Caption'),
        ),
    ]
