# Generated by Django 3.0.5 on 2020-06-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0007_auto_20200618_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True, help_text='Use this field for information that does not fit elsewhere.', max_length=1000, verbose_name='Notes'),
        ),
    ]
