# Generated by Django 3.0.5 on 2020-05-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0005_auto_20200528_1936'),
        ('collections_app', '0007_auto_20200529_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(default='', help_text='Create or choose a collector responsible for the collection.', on_delete=django.db.models.deletion.CASCADE, to='collectors_app.Collector', verbose_name='Collector'),
        ),
    ]
