# Generated by Django 3.0.5 on 2020-05-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0007_auto_20200507_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='coll_spec_formats',
        ),
        migrations.AlterField(
            model_name='collectionspecialformat',
            name='coll_special_format_thesaurus',
            field=models.CharField(choices=[('TGM', 'Thesaurus for Graphic Materials'), ('LCGFT', 'LC Genre/Form Terms'), ('Wikipedia', 'Wikipedia'), ('Other', 'Other')], max_length=10),
        ),
    ]
