# Generated by Django 3.0.5 on 2020-05-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0008_auto_20200507_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='coll_spec_format',
            field=models.ManyToManyField(blank=True, help_text='Add special formats contained in the collection, either analog or digital.', related_name='Collection', to='collections_app.CollectionSpecialFormat'),
        ),
    ]
