# Generated by Django 3.0.5 on 2020-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0008_auto_20200716_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='image',
            field=models.ImageField(help_text='Upload image showing example material from files and/or storage systems in use.<br />It seems reasonable to limit yourself to ten images per collection. Only five random images how in your collection detail view.</br />Show us the fun stuff!', upload_to='collection/images/', verbose_name='Image File'),
        ),
    ]
