# Generated by Django 3.0.5 on 2020-05-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0008_auto_20200512_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_size',
            field=models.TextField(default='', help_text='Provide a statement about the size of the collection, including growth rate, etc. Use whatever measurement terms are relevant.', max_length=1000),
        ),
    ]
