# Generated by Django 3.0.5 on 2020-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0008_collection_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='quote_attrib',
            field=models.CharField(blank=True, help_text='Provide the source of quote or tagline if applicable, including, at minimum, name, title, institution.', max_length=255, verbose_name='Quote Attribution'),
        ),
    ]
