# Generated by Django 3.0.5 on 2020-06-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0008_auto_20200529_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name'], 'verbose_name': 'Collection', 'verbose_name_plural': '** Collections'},
        ),
    ]
