# Generated by Django 3.0.5 on 2020-06-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0009_auto_20200601_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='quote_attrib',
            field=models.CharField(blank=True, help_text='Provide the source of the quote if applicable, including date.', max_length=255, verbose_name='Quote Attribution'),
        ),
    ]
