# Generated by Django 3.0.5 on 2020-06-29 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0009_auto_20200624_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Upload documents such as use guides or collection development statements.', upload_to='collection/documents/', verbose_name='Add Document')),
                ('doucument_caption', models.CharField(default='', help_text='Provide a short caption describing the document.', max_length=255, verbose_name='Document Caption')),
                ('collection', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='collections_app.Collection', verbose_name='Related Collection')),
            ],
            options={
                'verbose_name': 'Collection Document',
                'verbose_name_plural': 'Collection Documents',
            },
        ),
    ]
