# Generated by Django 3.0.5 on 2020-07-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0009_auto_20200716_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cat_system',
            field=models.ManyToManyField(blank=True, help_text='Add systems used for cataloging artist files collection. Hold down “Control” or “Command” to select more than one value.<br /><a href="/collections/cataloging_systems" target="blank">Create or update terms</a>, then return to this page to use.', related_name='collections', to='collections_app.CollectionCatSystem', verbose_name='Cataloging Systems'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='service',
            field=models.ManyToManyField(blank=True, help_text='Add reference services offered. Hold down “Control” or “Command” to select more than one value.<br /><a href="/collections/reference_services" target="blank">Create or update terms</a>, then return to this page to use.', related_name='collections', to='collections_app.CollectionService', verbose_name='Reference Services'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='spec_format',
            field=models.ManyToManyField(blank=True, help_text='Add special formats contained in the collection, either analog or digital. Hold down “Control” or “Command” to select more than one value.<br /><a href="/collections/special_formats" target="blank">Create or update terms</a>, then return to this page to use.', related_name='collections', to='collections_app.CollectionSpecialFormat', verbose_name='Special Formats'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subject_city',
            field=models.ManyToManyField(blank=True, help_text='Add cities that are subject focuses of the files. Hold down “Control” or “Command” to select more than one value.<br /><a href="/collections/subject_cities" target="blank">Create or update terms</a>, then return to this page to use.', related_name='collections', to='collections_app.CollectionSubjectCity', verbose_name='Subject: Cities'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subject_country',
            field=models.ManyToManyField(blank=True, help_text='Add countries that are subject focuses of the files. Hold down “Control” or “Command” to select more than one value.<br /><a href="/collections/subject_countries" target="blank">Create or update terms</a>, then return to this page to use.', related_name='collections', to='collections_app.CollectionSubjectCountry', verbose_name='Subject: Countries'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subject_county',
            field=models.ManyToManyField(blank=True, help_text='Add counties that are subject focuses of the files. Hold down “Control” or “Command” to select more than one value.<br /><a href="/collections/subject_counties" target="blank">Create or update terms</a>, then return to this page to use.', related_name='collections', to='collections_app.CollectionSubjectCounty', verbose_name='Subject: Counties'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subject_geo_area',
            field=models.ManyToManyField(blank=True, help_text='Add geographic areas, such as "West U.S." that are subject focuses of the files. Hold down “Control” or “Command” to select more than one value.<br /><a href="/collections/subject_geo_areas" target="blank">Create or update terms</a>, then return to this page to use.', related_name='collections', to='collections_app.CollectionSubjectGeoArea', verbose_name='Subject: Geographic Areas'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subject_name',
            field=models.ManyToManyField(blank=True, help_text='Add personal and institutional names that are subjects of the collection. Hold down “Control” or “Command” to select more than one value.<br /><a href="/collections/subject_names" target="blank">Create or update terms</a>, then return to this page to use.', related_name='collections', to='collections_app.CollectionSubjectName', verbose_name='Subject: Names'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subject_state_prov',
            field=models.ManyToManyField(blank=True, help_text='Add states or provinces that are subject focuses of the files. Hold down “Control” or “Command” to select more than one value.<br /><a href="/collections/subject_states_provinces" target="blank">Create or update terms</a>, then return to this page to use.', related_name='collections', to='collections_app.CollectionSubjectStateProv', verbose_name='Subject: States and Provinces'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subject_topic',
            field=models.ManyToManyField(blank=True, help_text='Add topical terms that are the subject focuses of the files. Hold down “Control” or “Command” to select more than one value.<br /><a href="/collections/subject_topics" target="blank">Create or update terms</a>, then return to this page to use.', related_name='collections', to='collections_app.CollectionSubjectTopic', verbose_name='Subject: Topics'),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='caption',
            field=models.CharField(default='', help_text='Provide a short yet descriptive caption describing the image. <br />Be very economical. 50 character limit, but shorter is better.', max_length=50, verbose_name='Caption'),
        ),
    ]
