# Generated by Django 3.0.5 on 2020-05-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0010_auto_20200508_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_name',
            field=models.CharField(blank=True, default='General Collection', help_text='Use "General Collection" if describing all files as one entry; otherwise, use for formal name of a collection or to describe a collection with special characteristics, for example The Nettie Wheeler Artist Files on Native American Artists.', max_length=255),
        ),
    ]
