# Generated by Django 3.0.5 on 2020-06-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0010_collectiondocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionimage',
            options={'ordering': ['image_caption'], 'verbose_name': 'Collection Image', 'verbose_name_plural': 'Collection Images'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='consortium',
            field=models.BooleanField(blank=True, help_text='Is this collection a consortial or collaborative collection?', verbose_name='Consortial&nbsp;Collection?'),
        ),
    ]
