# Generated by Django 3.0.5 on 2020-06-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0010_collection_quote_attrib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='quote',
            field=models.TextField(blank=True, help_text='Provide an quotable quote or tagline for the collection. Quotes will automatically be added.', max_length=500, verbose_name='Quote'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='quote_attrib',
            field=models.CharField(blank=True, help_text='Provide the source of quote or tagline if applicable, including name, title, date, etc.', max_length=255, verbose_name='Quote Attribution'),
        ),
    ]
