# Generated by Django 3.0.5 on 2020-05-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0011_auto_20200508_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_description',
            field=models.TextField(help_text='Provide a general description of the collection, including such aspects as history, provenance, and size.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_name',
            field=models.CharField(default='General Collection', help_text='Use "General Collection" if describing all files as one entry; otherwise, use for formal name of a collection or to describe a collection with special characteristics, for example The Nettie Wheeler Artist Files on Native American Artists.', max_length=255),
        ),
    ]
