# Generated by Django 3.0.5 on 2020-06-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0011_auto_20200601_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='quote',
            field=models.TextField(blank=True, help_text='Provide a quote or tagline for the collection. Quotes are automatically added.', max_length=500, verbose_name='Quote'),
        ),
    ]
