# Generated by Django 3.0.5 on 2020-06-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0012_auto_20200601_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='quote_attrib',
            field=models.CharField(blank=True, help_text='Provide the source of quote or tagline if applicable, including name, title, date, publication source, etc.', max_length=255, verbose_name='Quote Attribution'),
        ),
    ]
