# Generated by Django 3.0.5 on 2020-06-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0012_auto_20200630_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='consortium',
            field=models.BooleanField(blank=True, help_text='Check if this collection is a consortial or collaborative.', verbose_name='Consortial Collection?'),
        ),
    ]
