# Generated by Django 3.0.5 on 2020-06-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0025_auto_20200603_2226'),
        ('collections_app', '0013_auto_20200601_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(default='', help_text='Create or choose a collector responsible for the artist files collection.', on_delete=django.db.models.deletion.CASCADE, to='collectors_app.Collector', verbose_name='Collector'),
        ),
    ]
