# Generated by Django 3.0.5 on 2020-06-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0013_auto_20200630_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='consortium',
            field=models.BooleanField(blank=True, help_text='Check if this collection has more than one associated collector.', verbose_name='Consortial Collection?'),
        ),
    ]
