# Generated by Django 3.0.5 on 2020-05-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0013_auto_20200513_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_image',
            field=models.ForeignKey(blank=True, help_text='Upload images showing example material from files and/or storage systems in use.', null=True, on_delete=django.db.models.deletion.CASCADE, to='collections_app.CollectionImage', verbose_name='Collection Images'),
        ),
    ]
