# Generated by Django 3.0.5 on 2020-05-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0013_auto_20200508_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsubjecttopic',
            name='coll_sub_thesaurus',
            field=models.CharField(choices=[('LCSH', 'Library of Congress Subject Headings'), ('AAT', 'Art and Architecture Thesaurus')], default='LCSH', max_length=10),
        ),
    ]
