# Generated by Django 3.0.5 on 2020-06-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0014_auto_20200630_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='consortium',
            field=models.BooleanField(blank=True, help_text='Check if you have selected more than one associated collector in the field above.', verbose_name='Consortial Collection?'),
        ),
    ]
