# Generated by Django 3.0.5 on 2020-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0014_auto_20200513_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_dig_projects',
            field=models.TextField(blank=True, help_text='Describe digital projects, either completed or planned, for this collection.', max_length=1000, verbose_name='Digital Projects'),
        ),
    ]
