# Generated by Django 3.0.5 on 2020-06-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0014_auto_20200603_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='access',
            field=models.TextField(blank=True, help_text='Add policies and procedures relating to how researchers access and use the collection.', max_length=1000, verbose_name='Access and Use'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='cat_system',
            field=models.ManyToManyField(blank=True, help_text='Add systems used for cataloging artist files collection. Create a new system if there is not a fit.', related_name='collections', to='collections_app.CollectionCatSystem', verbose_name='Cataloging Systems'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a general description of the collection, including such aspects as history and provenance. Also use this field for general notes about the collection.', max_length=3000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dig_projects',
            field=models.TextField(blank=True, help_text='Describe digital projects, either completed or planned, for this collection.', max_length=3000, verbose_name='Digital Projects'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='service',
            field=models.ManyToManyField(blank=True, help_text='Add reference services offered. Create a new service if there is not a fit.', related_name='collections', to='collections_app.CollectionService', verbose_name='Reference Services'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='size',
            field=models.TextField(blank=True, default='', help_text='Provide a statement about the size of the collection, including growth rate, etc. Use whatever measurement terms are relevant.', max_length=1000, verbose_name='Size'),
        ),
    ]
