# Generated by Django 3.0.5 on 2020-05-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0015_auto_20200513_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='coll_image',
            field=models.ImageField(help_text='Upload images showing example material from files and/or storage systems in use.', upload_to='collection/images/', verbose_name='Add Image'),
        ),
    ]
