# Generated by Django 3.0.5 on 2020-07-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0015_auto_20200630_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='image_caption',
            field=models.CharField(default='', help_text='Provide a short caption describing the document.', max_length=50, verbose_name='Image Caption'),
        ),
    ]
