# Generated by Django 3.0.5 on 2020-05-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0016_auto_20200513_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionspecialformat',
            name='coll_special_format',
            field=models.CharField(max_length=100, verbose_name='Special Formats'),
        ),
    ]
