# Generated by Django 3.0.5 on 2020-07-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0017_auto_20200701_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='image_caption',
            field=models.CharField(default='', help_text='Provide a short yet descriptive caption describing the image. 50 character limit.', max_length=50, verbose_name='Image Caption'),
        ),
    ]
