# Generated by Django 3.0.5 on 2020-07-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0019_auto_20200701_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='consortium',
            field=models.BooleanField(blank=True, help_text='Check if you have selected more than one collector in the field above.', verbose_name='Consortial Collection?'),
        ),
    ]
