# Generated by Django 3.0.5 on 2020-05-08 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0002_remove_institution_inst_coll'),
        ('persons_app', '0008_auto_20200507_2025'),
        ('collections_app', '0020_auto_20200508_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='coll_institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions_app.Institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='coll_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='persons_app.Person'),
            preserve_default=False,
        ),
    ]
