# Generated by Django 3.0.5 on 2020-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors_app', '0036_auto_20200605_1545'),
        ('collections_app', '0020_auto_20200609_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collector_mul',
            field=models.ManyToManyField(blank=True, help_text='Create or choose a collector responsible for the artist files collection. A collection can have multiple owners, for example, in the case of consortial digital projects.', related_name='collections', to='collectors_app.Collector', verbose_name='Collector(s)'),
        ),
    ]
