# Generated by Django 3.0.5 on 2020-07-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0020_auto_20200701_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectiondocument',
            options={'ordering': ['document_caption'], 'verbose_name': 'Collection Document', 'verbose_name_plural': 'Collection Documents'},
        ),
        migrations.RenameField(
            model_name='collectiondocument',
            old_name='doucument_caption',
            new_name='document_caption',
        ),
    ]
