# Generated by Django 3.0.5 on 2020-07-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0020_auto_20200722_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='dig_bool',
            field=models.BooleanField(blank=True, default=False, help_text='Check if collection has been fully or partially digitized content or if there are plans to offer digital access.', verbose_name='Digital'),
        ),
    ]
