# Generated by Django 3.0.5 on 2020-05-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0020_auto_20200513_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionlanguage',
            options={'ordering': ['coll_lang'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
    ]
