# Generated by Django 3.0.5 on 2020-07-24 14:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0021_collection_dig_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='consortium_desc',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Provide details about the consortial/shared collection.', max_length=3000, verbose_name='Consortium Description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='consortium',
            field=models.BooleanField(blank=True, help_text='Check if you have selected more than one collector in the collector `field above.', verbose_name='Consortial Collection?'),
        ),
    ]
