# Generated by Django 3.0.5 on 2020-05-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0021_auto_20200508_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='coll_institution',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='coll_person',
        ),
    ]
