# Generated by Django 3.0.5 on 2020-05-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0021_auto_20200513_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionsubjectgeoarea',
            options={'ordering': ['coll_sub_geo_area'], 'verbose_name': 'Subject - Geographic Area', 'verbose_name_plural': 'Subject - Geographic Areas'},
        ),
        migrations.AlterField(
            model_name='collectionlanguage',
            name='coll_lang',
            field=models.CharField(help_text='Use language term from http://id.loc.gov/vocabulary/languages.html', max_length=100, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='collectionlanguage',
            name='coll_lang_url',
            field=models.URLField(help_text='Provide URI for term from http://id.loc.gov/vocabulary/languages.html', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100, verbose_name='Geographic Area Term'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255, verbose_name='Thesaurus Term'),
        ),
    ]
