# Generated by Django 3.0.5 on 2020-07-06 18:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0022_afruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Provide a general description of the collection, including such aspects as history and provenance. Also use this field for general notes about the collection.', max_length=3000, verbose_name='Description'),
        ),
    ]
