# Generated by Django 3.0.5 on 2020-05-09 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0022_auto_20200508_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['coll_name']},
        ),
    ]
