# Generated by Django 3.0.5 on 2020-05-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0022_auto_20200513_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['coll_name'], 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='collectioncatsystem',
            options={'ordering': ['coll_cat_name'], 'verbose_name': 'Cataloging System', 'verbose_name_plural': 'Cataloging Systems'},
        ),
        migrations.AlterModelOptions(
            name='collectionservice',
            options={'ordering': ['coll_serv_name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='collectionspecialformat',
            options={'ordering': ['coll_special_format'], 'verbose_name': 'Special Format', 'verbose_name_plural': 'Special Formats'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjectcity',
            options={'ordering': ['coll_sub_city'], 'verbose_name': 'Subject - City', 'verbose_name_plural': 'Subject - Cities'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjectcountry',
            options={'ordering': ['coll_sub_country'], 'verbose_name': 'Subject - Country', 'verbose_name_plural': 'Subject - Countries'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjectcounty',
            options={'ordering': ['coll_sub_county'], 'verbose_name': 'Subject - County', 'verbose_name_plural': 'Subject - Counties'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjectname',
            options={'ordering': ['coll_sub_name'], 'verbose_name': 'Subject - Name', 'verbose_name_plural': 'Subject - Names'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjectstateprov',
            options={'ordering': ['coll_sub_state_prov'], 'verbose_name': 'Subject - State/Province', 'verbose_name_plural': 'Subject - State/Provinces '},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjecttopic',
            options={'ordering': ['coll_sub_topic'], 'verbose_name': 'Subject - Topic', 'verbose_name_plural': 'Subject - Topics'},
        ),
        migrations.AlterField(
            model_name='collectioncatsystem',
            name='coll_cat_name',
            field=models.CharField(max_length=100, verbose_name='Cataloging Systems'),
        ),
        migrations.AlterField(
            model_name='collectionservice',
            name='coll_serv_name',
            field=models.CharField(max_length=100, verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100, verbose_name='Subject City'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city_url',
            field=models.URLField(default='', help_text='Provide VIAF permalink.', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100, verbose_name='Subject - Country'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255, verbose_name='Thesauras Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcounty',
            name='coll_sub_county',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100, verbose_name='Subject - County'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcounty',
            name='coll_sub_county_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectname',
            name='coll_sub_name',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100, verbose_name='Subject - Name'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectname',
            name='coll_sub_name_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectstateprov',
            name='coll_sub_state_prov',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100, verbose_name='Subject - State/Province'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectstateprov',
            name='coll_sub_state_prov_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjecttopic',
            name='coll_sub_thesaurus',
            field=models.CharField(choices=[('LCSH', 'Library of Congress Subject Headings'), ('AAT', 'Art and Architecture Thesaurus')], default='LCSH', max_length=10, verbose_name='Thesaurus'),
        ),
        migrations.AlterField(
            model_name='collectionsubjecttopic',
            name='coll_sub_topic',
            field=models.CharField(max_length=100, verbose_name='Subject - Topic'),
        ),
        migrations.AlterField(
            model_name='collectionsubjecttopic',
            name='coll_sub_topic_url',
            field=models.URLField(default='', help_text='Provide permalink from id.loc.gov or vocab.getty.edu.', max_length=255, verbose_name='Thesaurus Website'),
        ),
    ]
