# Generated by Django 3.0.5 on 2020-05-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0023_auto_20200514_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country_url',
            field=models.URLField(help_text='Provide VIAF permalink.', max_length=255, verbose_name='Thesaurus Website'),
        ),
    ]
