# Generated by Django 3.0.5 on 2020-07-06 18:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0023_auto_20200706_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='access',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Add policies and procedures relating to how researchers access and use the collection.', max_length=1000, verbose_name='Access and Use'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dig_projects',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Describe digital projects, either completed or planned, for this collection.', max_length=3000, verbose_name='Digital Projects'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='quote',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Provide a quote or tagline for the collection. Quotes get automatically added.', max_length=500, verbose_name='Quote'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='size',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Provide a statement about the size of the collection, including growth rate, etc. Use whatever measurement terms are relevant.', max_length=1000, verbose_name='Size'),
        ),
    ]
