# Generated by Django 3.0.5 on 2020-06-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0023_auto_20200611_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='subject_city',
            field=models.ManyToManyField(blank=True, help_text='Add cities that are subject focuses of the files.', related_name='collections', to='collections_app.CollectionSubjectCity', verbose_name='Subject: Cities'),
        ),
    ]
