# Generated by Django 3.0.5 on 2020-06-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0024_auto_20200615_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='consortium',
            field=models.BooleanField(blank=True, default=False, help_text='Is this collection a consortial or collaborative collection?', verbose_name='Consortium?'),
            preserve_default=False,
        ),
    ]
