# Generated by Django 3.0.5 on 2020-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0024_auto_20200515_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionservice',
            options={'ordering': ['coll_serv_name'], 'verbose_name': 'Reference Service', 'verbose_name_plural': 'Reference Services'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_services',
            field=models.ManyToManyField(help_text='Add reference services offered. Create a new service if there is not a fit.', related_name='Collection', to='collections_app.CollectionService', verbose_name='Reference Services'),
        ),
        migrations.AlterField(
            model_name='collectionservice',
            name='coll_serv_name',
            field=models.CharField(max_length=100, verbose_name='Reference Services'),
        ),
    ]
