# Generated by Django 3.0.5 on 2020-07-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0024_auto_20200724_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='consortium',
            field=models.BooleanField(blank=True, help_text='Check if you have selected more than one collector in the collector field above.', verbose_name='Consortial Collection?'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='consortium_url',
            field=models.URLField(blank=True, help_text='Add website for consortial/shared collection.', max_length=255, verbose_name='Consortial Website'),
        ),
    ]
