# Generated by Django 3.0.5 on 2020-06-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0025_collection_consortium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='consortium',
            field=models.BooleanField(blank=True, help_text='Is this collection a consortial or collaborative collection?', verbose_name='Consortial collection?'),
        ),
    ]
