# Generated by Django 3.0.5 on 2020-07-07 17:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0025_auto_20200706_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='quote',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Provide a pithy quote or tagline for the collection.', max_length=500, verbose_name='Quote'),
        ),
    ]
