# Generated by Django 3.0.5 on 2020-05-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0025_auto_20200509_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_description',
            field=models.TextField(help_text='Provide a general description of the collection, including such aspects as history, provenance, and size. Also use this field for general notes about the collection.', max_length=1000),
        ),
    ]
