# Generated by Django 3.0.5 on 2020-05-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0025_auto_20200518_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjectcity',
            options={'ordering': ['coll_sub_city'], 'verbose_name': 'Subject: City', 'verbose_name_plural': 'Subject: Cities'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjectcountry',
            options={'ordering': ['coll_sub_country'], 'verbose_name': 'Subject: Country', 'verbose_name_plural': 'Subject: Countries'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjectcounty',
            options={'ordering': ['coll_sub_county'], 'verbose_name': 'Subject: County', 'verbose_name_plural': 'Subject: Counties'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjectgeoarea',
            options={'ordering': ['coll_sub_geo_area'], 'verbose_name': 'Subject: Geographic Area', 'verbose_name_plural': 'Subject: Geographic Areas'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjectname',
            options={'ordering': ['coll_sub_name'], 'verbose_name': 'Subject: Name', 'verbose_name_plural': 'Subject: Names'},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjectstateprov',
            options={'ordering': ['coll_sub_state_prov'], 'verbose_name': 'Subject: State/Province', 'verbose_name_plural': 'Subject: State/Provinces '},
        ),
        migrations.AlterModelOptions(
            name='collectionsubjecttopic',
            options={'ordering': ['coll_sub_topic'], 'verbose_name': 'Subject: Topic', 'verbose_name_plural': 'Subject: Topics'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_loc_city',
            field=models.CharField(help_text='Important for providing access to collections located in specific cities.', max_length=255, verbose_name='Location: City'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_loc_country',
            field=models.CharField(help_text='Important for providing access to collections located in specific countries.', max_length=255, verbose_name='Location: Country'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_loc_state_prov',
            field=models.CharField(help_text='Important for providing access to collections located in specific states or provinces.', max_length=255, verbose_name='Location: State/Province'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100, verbose_name='Subject: City'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100, verbose_name='Subject: Country'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcounty',
            name='coll_sub_county',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100, verbose_name='Subject: County'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100, verbose_name='Subject: Geographic Area'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectstateprov',
            name='coll_sub_state_prov',
            field=models.CharField(help_text='Use preferred VIAF form of name.', max_length=100, verbose_name='Subject: State/Province'),
        ),
        migrations.AlterField(
            model_name='collectionsubjecttopic',
            name='coll_sub_topic',
            field=models.CharField(max_length=100, verbose_name='Subject: Topic'),
        ),
    ]
