# Generated by Django 3.0.5 on 2020-07-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0026_auto_20200707_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='quote',
            field=models.TextField(blank=True, help_text='Provide a pithy quote or tagline for the collection. This field automatically adds quotes.', max_length=500, verbose_name='Quote'),
        ),
    ]
