# Generated by Django 3.0.5 on 2020-05-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0026_auto_20200518_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_city',
            field=models.ManyToManyField(blank=True, help_text='Add cities that are subject focuses of the files', related_name='Collection', to='collections_app.CollectionSubjectCity', verbose_name='Subject: Cities'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_country',
            field=models.ManyToManyField(blank=True, help_text='Add countries that are subject focuses of the files.', related_name='Collection', to='collections_app.CollectionSubjectCountry', verbose_name='Subject: Countries'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_county',
            field=models.ManyToManyField(blank=True, help_text='Add counties that are subject focuses of the files.', related_name='Collection', to='collections_app.CollectionSubjectCounty', verbose_name='Subject: Counties'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_geo_area',
            field=models.ManyToManyField(blank=True, help_text='Add geographic areas, such as "West U.S." that are subject focuses of the files.', related_name='Collection', to='collections_app.CollectionSubjectGeoArea', verbose_name='Subject: Geographic Areas'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_name',
            field=models.ManyToManyField(blank=True, help_text='Add personal and institutional names that are subjects of the collection.', related_name='Collection', to='collections_app.CollectionSubjectName', verbose_name='Subject: Names'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_state_prov',
            field=models.ManyToManyField(blank=True, help_text='Add states or provinces that are subject focuses of the files.', related_name='Collection', to='collections_app.CollectionSubjectStateProv', verbose_name='Subject: States and Provinces'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_subject_topic',
            field=models.ManyToManyField(blank=True, help_text='Add topical terms that are the subject focuses of the files.', related_name='Collection', to='collections_app.CollectionSubjectTopic', verbose_name='Subject: Topics'),
        ),
    ]
