# Generated by Django 3.0.5 on 2020-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0026_auto_20200509_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='coll_size',
            field=models.TextField(default='', help_text='Provide, in whatever terms relevant, a statement about the size of the collection, including growth rate, etc.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_description',
            field=models.TextField(help_text='Provide a general description of the collection, including such aspects as history and provenance. Also use this field for general notes about the collection.', max_length=1000),
        ),
    ]
