# Generated by Django 3.0.5 on 2020-05-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0027_auto_20200518_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionsubjecttopic',
            name='coll_sub_thesaurus',
        ),
        migrations.AlterField(
            model_name='collectioncatsystem',
            name='coll_cat_name',
            field=models.CharField(help_text='Add a new cataloging system.', max_length=100, verbose_name='Cataloging Systems'),
        ),
        migrations.AlterField(
            model_name='collectionlanguage',
            name='coll_lang',
            field=models.CharField(help_text='Use authorized form from <a href="http://id.loc.gov/vocabulary/languages.html">MARC List for Languages</a> or other authority.', max_length=100, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='collectionlanguage',
            name='coll_lang_url',
            field=models.URLField(help_text='Provide URI to term.', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionservice',
            name='coll_serv_name',
            field=models.CharField(help_text='Add a new reference service.', max_length=100, verbose_name='Reference Services'),
        ),
        migrations.AlterField(
            model_name='collectionspecialformat',
            name='coll_special_format',
            field=models.CharField(help_text='Add a new special format.', max_length=100, verbose_name='Special Format Name'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city',
            field=models.CharField(help_text='Use authorized form from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: City'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city_url',
            field=models.URLField(default='', help_text='Provide URI to term.', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country',
            field=models.CharField(help_text='Use authorized form from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: Country'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country_url',
            field=models.URLField(help_text='Provide URI to term.', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcounty',
            name='coll_sub_county',
            field=models.CharField(help_text='Use authorized form from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: County'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcounty',
            name='coll_sub_county_url',
            field=models.URLField(help_text='Provide URI to term.', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area',
            field=models.CharField(help_text='Use authorized form from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: Geographic Area'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area_url',
            field=models.URLField(help_text='Provide URI to term.', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectstateprov',
            name='coll_sub_state_prov',
            field=models.CharField(help_text='Use authorized form from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: State/Province'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectstateprov',
            name='coll_sub_state_prov_url',
            field=models.URLField(help_text='Provide URI to term.', max_length=255, verbose_name='Thesaurus Website'),
        ),
        migrations.AlterField(
            model_name='collectionsubjecttopic',
            name='coll_sub_topic',
            field=models.CharField(help_text='Use authorized form from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: Topic'),
        ),
        migrations.AlterField(
            model_name='collectionsubjecttopic',
            name='coll_sub_topic_url',
            field=models.URLField(default='', help_text='Provide URI to term.', max_length=255, verbose_name='Thesaurus Website'),
        ),
    ]
