# Generated by Django 3.0.5 on 2020-05-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0027_auto_20200509_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_cat_system',
            field=models.ManyToManyField(help_text='Add systems used for cataloging artist files collection. Create a new type if there is not a fit.', related_name='Collection', to='collections_app.CollectionCatSystem'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_images',
            field=models.ImageField(blank=True, help_text='Upload images showing storage systems and/or example material from files. First image will be used as featured image in directory listing.', upload_to='collection/images/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_services',
            field=models.ManyToManyField(help_text='Add reference services offered. Create a new type if there is not a fit.', related_name='Collection', to='collections_app.CollectionService'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_spec_format',
            field=models.ManyToManyField(blank=True, help_text='Add special formats contained in the collection, either analog or digital. Create a new type if there is not a fit.', related_name='Collection', to='collections_app.CollectionSpecialFormat'),
        ),
    ]
