# Generated by Django 3.0.5 on 2020-06-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0027_auto_20200616_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionLanguage',
        ),
    ]
