# Generated by Django 3.0.5 on 2020-05-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0028_auto_20200518_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlanguage',
            name='coll_lang',
            field=models.CharField(help_text='Use language term from <a href="http://id.loc.gov/vocabulary/languages.html">MARC List for Languages</a> or other authority.', max_length=100, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: City'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: Country'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcounty',
            name='coll_sub_county',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: County'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: Geographic Area'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectstateprov',
            name='coll_sub_state_prov',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: State/Province'),
        ),
        migrations.AlterField(
            model_name='collectionsubjecttopic',
            name='coll_sub_topic',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: Topic'),
        ),
    ]
