# Generated by Django 3.0.5 on 2020-06-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0028_delete_collectionlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='images',
            field=models.ImageField(default='', help_text='Upload images showing example material from files and/or storage systems in use.', upload_to='collection/images/', verbose_name='Add Image'),
        ),
    ]
