# Generated by Django 3.0.5 on 2020-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0028_auto_20200509_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_cat_system',
            field=models.ManyToManyField(help_text='Add systems used for cataloging artist files collection. Create a new system if there is not a fit.', related_name='Collection', to='collections_app.CollectionCatSystem'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='coll_services',
            field=models.ManyToManyField(help_text='Add reference services offered. Create a new service if there is not a fit.', related_name='Collection', to='collections_app.CollectionService'),
        ),
    ]
