# Generated by Django 3.0.5 on 2020-05-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0029_auto_20200509_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsubjecttopic',
            name='coll_sub_topic_url',
            field=models.URLField(default='', help_text='Provide permalink from id.loc.gov or vocab.getty.edu.', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city_url',
            field=models.URLField(default='', help_text='Provide VIAF permalink.', max_length=255),
        ),
    ]
