# Generated by Django 3.0.5 on 2020-06-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0029_collection_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='images',
        ),
    ]
