# Generated by Django 3.0.5 on 2020-05-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0031_auto_20200518_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionspecialformat',
            name='coll_special_format_thesaurus',
        ),
        migrations.AlterField(
            model_name='collectionspecialformat',
            name='coll_special_format_url',
            field=models.URLField(blank=True, help_text='Provide URI from <a href="http://id.loc.gov/vocabulary/graphicMaterials.html" target="_blank">TGM</a>, <a href="http://id.loc.gov/authorities/genreForms.html" target="_blank">LCGFT</a>, Wikipedia URL, or other URL.', max_length=255, verbose_name='Format Reference'),
        ),
    ]
