# Generated by Django 3.0.5 on 2020-07-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0031_auto_20200727_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='quote',
            field=models.TextField(blank=True, help_text='Provide a pithy quote or tagline for the collection. A quote makes the entry look better, besides rounding out the description. teThis field automatically adds quotes.', max_length=500, verbose_name='Quote'),
        ),
    ]
