# Generated by Django 3.0.5 on 2020-05-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0032_auto_20200518_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlanguage',
            name='coll_lang_url',
            field=models.URLField(blank=True, help_text='Provide URI to term.', max_length=255, verbose_name='Language Name Reference'),
        ),
        migrations.AlterField(
            model_name='collectionspecialformat',
            name='coll_special_format_url',
            field=models.URLField(blank=True, help_text='Provide URI from <a href="http://id.loc.gov/vocabulary/graphicMaterials.html" target="_blank">TGM</a>, <a href="http://id.loc.gov/authorities/genreForms.html" target="_blank">LCGFT</a>, <a href="http://www.wikipedia.org" target="_blank">Wikipedia</a> URL, or other URL.', max_length=255, verbose_name='Format Name Reference'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city_url',
            field=models.URLField(blank=True, default='', help_text='Provide URI to term.', max_length=255, verbose_name='Term Reference'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country_url',
            field=models.URLField(help_text='Provide URI to term.', max_length=255, verbose_name='Term Reference'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcounty',
            name='coll_sub_county_url',
            field=models.URLField(blank=True, help_text='Provide URI to term.', max_length=255, verbose_name='Term Reference'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area_url',
            field=models.URLField(blank=True, help_text='Provide URI to term.', max_length=255, verbose_name='Term Reference'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectname',
            name='coll_sub_name',
            field=models.CharField(blank='False', help_text='Use preferred <a href="http://www.viaf.org" target="_blank">VIAF</a> form of name.', max_length=100, verbose_name='Subject: Name'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectname',
            name='coll_sub_name_url',
            field=models.URLField(help_text='Provide <a href="http://www.viaf.org" target="_blank">VIAF</a> permalink.', max_length=255, verbose_name='Form of Name Reference'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectstateprov',
            name='coll_sub_state_prov_url',
            field=models.URLField(blank=True, help_text='Provide URI to term.', max_length=255, verbose_name='Term Reference'),
        ),
        migrations.AlterField(
            model_name='collectionsubjecttopic',
            name='coll_sub_topic_url',
            field=models.URLField(blank=True, default='', help_text='Provide URI to term.', max_length=255, verbose_name='Term Reference'),
        ),
    ]
