# Generated by Django 3.0.5 on 2020-05-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0035_auto_20200518_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncatsystem',
            name='coll_cat_name',
            field=models.CharField(max_length=100, verbose_name='Cataloging Systems'),
        ),
        migrations.AlterField(
            model_name='collectionlanguage',
            name='coll_lang',
            field=models.CharField(help_text='Use language term from <a href="http://id.loc.gov/vocabulary/languages.html" target="_blank">MARC List for Languages</a> or other authority.', max_length=100, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='collectionservice',
            name='coll_serv_name',
            field=models.CharField(max_length=100, verbose_name='Reference Services'),
        ),
        migrations.AlterField(
            model_name='collectionspecialformat',
            name='coll_special_format',
            field=models.CharField(max_length=100, verbose_name='Special Format Name'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: City'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">LCSH </a> or other authority.', max_length=100, verbose_name='Subject: Country'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcounty',
            name='coll_sub_county',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">LCSH </a> or other authority.', max_length=100, verbose_name='Subject: County'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">LCSH </a> or other authority.', max_length=100, verbose_name='Subject: Geographic Area'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectname',
            name='coll_sub_name',
            field=models.CharField(blank='False', help_text='Use preferred <a href="http://www.viaf.org" target="_blank">VIAF</a> form of name.', max_length=100, verbose_name='Subject: Name'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectstateprov',
            name='coll_sub_state_prov',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">LCSH</a> or other authority.', max_length=100, verbose_name='Subject: State/Province'),
        ),
        migrations.AlterField(
            model_name='collectionsubjecttopic',
            name='coll_sub_topic',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">LCSH </a> or other authority.', max_length=100, verbose_name='Subject: Topic'),
        ),
    ]
