# Generated by Django 3.0.5 on 2020-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0035_auto_20200813_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='caption',
            field=models.CharField(default='', help_text='Provide a short yet descriptive caption describing the image. <br />Be very economical: 50 character limit, but shorter is better.', max_length=50, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='collectionimage',
            name='image',
            field=models.ImageField(help_text='Upload image showing example material from files and/or storage systems in use.<br />It seems reasonable to limit yourself to ten images per collection, less is better. Only five random images show in your collection detail view. The directory favors images with square ratios orientation, otherwise automatic cropping to a square can be unpredictable.</br /> Show off your special material!', upload_to='collection/images/', verbose_name='Image File'),
        ),
    ]
