# Generated by Django 3.0.5 on 2020-05-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0036_auto_20200518_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncatsystem',
            name='coll_cat_name',
            field=models.CharField(max_length=100, verbose_name='Cataloging System'),
        ),
        migrations.AlterField(
            model_name='collectionservice',
            name='coll_serv_name',
            field=models.CharField(max_length=100, verbose_name='Reference Service'),
        ),
        migrations.AlterField(
            model_name='collectionspecialformat',
            name='coll_special_format',
            field=models.CharField(max_length=100, verbose_name='Special Format'),
        ),
    ]
