# Generated by Django 3.0.5 on 2020-05-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0037_auto_20200518_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionspecialformat',
            name='coll_special_format_url',
            field=models.URLField(blank=True, help_text='Provide URI from <a href="http://id.loc.gov/vocabulary/graphicMaterials.html" target="_blank">Thesaurus for Graphic Materials</a>, <a href="http://id.loc.gov/authorities/genreForms.html" target="_blank">Library of Congress Genre/Form Terms</a>, <a href="http://www.wikipedia.org" target="_blank">Wikipedia</a> URL, or other URL.', max_length=255, verbose_name='Term Reference'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcity',
            name='coll_sub_city',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">Library of Congress Subject Headings</a> or other authority.', max_length=100, verbose_name='Subject: City'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcountry',
            name='coll_sub_country',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">Library of Congress Subject Headings </a> or other authority.', max_length=100, verbose_name='Subject: Country'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectcounty',
            name='coll_sub_county',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">Library of Congress Subject Headings </a> or other authority.', max_length=100, verbose_name='Subject: County'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectgeoarea',
            name='coll_sub_geo_area',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">Library of Congress Subject Headings </a> or other authority.', max_length=100, verbose_name='Subject: Geographic Area'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectstateprov',
            name='coll_sub_state_prov',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">Library of Congress Subject Headings</a> or other authority.', max_length=100, verbose_name='Subject: State/Province'),
        ),
        migrations.AlterField(
            model_name='collectionsubjecttopic',
            name='coll_sub_topic',
            field=models.CharField(help_text='Use term from <a href="http://id.loc.gov/authorities/subjects.html" target="_blank">Library of Congress Subject Headings </a> or other authority.', max_length=100, verbose_name='Subject: Topic'),
        ),
    ]
