# Generated by Django 3.0.5 on 2020-08-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0037_auto_20200819_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='image',
            field=models.ImageField(help_text='Upload image showing example material from files and/or storage systems in use. It seems reasonable to limit yourself to ten images per collection, less is better. Only five random images show in your collection detail view. The directory favors square images, otherwise automatic square cropping can be unpredictable. Show off your special material!', upload_to='collection/images/', verbose_name='Image File'),
        ),
    ]
