# Generated by Django 3.0.5 on 2020-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0038_auto_20200819_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='image',
            field=models.ImageField(help_text='Upload image showing example material from files and/or storage systems in use. Ten images seems reasonable per collection, less is better. Only five random images show in your collection detail view. The directory favors square images, otherwise automatic square cropping can be unpredictable. Show off your special material!', upload_to='collection/images/', verbose_name='Image File'),
        ),
    ]
