# Generated by Django 3.0.5 on 2020-05-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0038_auto_20200518_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsubjectname',
            name='coll_sub_name',
            field=models.CharField(help_text='Use preferred <a href="http://www.viaf.org" target="_blank">VIAF</a> form of name. Remove delimiters and subfields.', max_length=100, verbose_name='Subject: Name'),
        ),
        migrations.AlterField(
            model_name='collectionsubjectname',
            name='coll_sub_name_url',
            field=models.URLField(blank=True, help_text='Provide <a href="http://www.viaf.org" target="_blank">VIAF</a> permalink.', max_length=255, verbose_name='Form of Name Reference'),
        ),
    ]
