# Generated by Django 3.0.5 on 2020-05-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0041_auto_20200519_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='coll_description',
            field=models.TextField(help_text='Provide a general description of the collection, including such aspects as history and provenance. Also use this field for general notes about the collection.', max_length=2000, verbose_name='Description'),
        ),
    ]
