# Generated by Django 3.0.5 on 2020-05-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0044_auto_20200521_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='quote',
            field=models.TextField(blank=True, help_text='Provide an interested quote or tagline for the collection.', max_length=500, verbose_name='Quote'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Upload images showing example material from files and/or storage systems in use.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Collection', to='collections_app.CollectionImage', verbose_name='Collection Images'),
        ),
    ]
