# Generated by Django 3.0.5 on 2020-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0045_auto_20200521_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='quote',
            field=models.TextField(blank=True, help_text='Provide an quotable quote or tagline for the collection.', max_length=500, verbose_name='Quote'),
        ),
    ]
