# Generated by Django 3.0.5 on 2020-05-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_last_name', models.CharField(max_length=255)),
                ('per_first_name', models.CharField(max_length=255)),
                ('per_email', models.EmailField(blank=True, max_length=255)),
                ('per_tel', models.CharField(blank=True, max_length=50)),
                ('per_website', models.URLField(blank=True, max_length=255)),
                ('per_date_created', models.DateField(auto_now_add=True)),
                ('per_date_saved', models.DateField(auto_now=True)),
                ('per_collection', models.ForeignKey(help_text='Create an artist files collection and provide details. Multiple collections allowed and encouraged. Create a separate entry for each formally named collection or collection with special characteristics, for example "The Nettie Wheeler Artist Files on Native American Artists."', on_delete=django.db.models.deletion.CASCADE, to='collections_app.Collection')),
                ('per_type', models.ManyToManyField(help_text='Choose all roles that are relevant. Create new role if there is not a fit.', related_name='Person', to='persons_app.PersonType')),
            ],
            options={
                'ordering': ['per_last_name'],
            },
        ),
    ]
