# Generated by Django 3.0.5 on 2020-05-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_last_name', models.CharField(max_length=255)),
                ('per_first_name', models.CharField(max_length=255)),
                ('pers_email', models.EmailField(max_length=255)),
                ('pers_tel', models.CharField(max_length=50, null=True)),
                ('per_website', models.URLField(max_length=255, null=True)),
                ('per_type', models.ManyToManyField(related_name='Person', to='persons_app.PersonType')),
            ],
        ),
    ]
