# Generated by Django 3.0.5 on 2020-05-01 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['per_last_name']},
        ),
        migrations.AlterModelOptions(
            name='persontype',
            options={'ordering': ['type_name']},
        ),
    ]
