# Generated by Django 3.0.5 on 2020-05-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0013_auto_20200513_1501'),
        ('persons_app', '0002_auto_20200512_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='per_collection',
            field=models.ForeignKey(help_text='Create an artist files collection and provide details. Use "General Collection" if describing all files as one combined entry. Create a separate entry for each formally named collection or collection with special characteristics, for example "The Nettie Wheeler Artist Files on Native American Artists." Multiple collections allowed and encouraged.', on_delete=django.db.models.deletion.CASCADE, to='collections_app.Collection', verbose_name='Add Collection'),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_last_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_tel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_type',
            field=models.ManyToManyField(help_text='Choose all roles that are relevant. Create new role if there is not a fit.', related_name='Person', to='persons_app.PersonType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_website',
            field=models.URLField(blank=True, max_length=255, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='type_name',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
    ]
