# Generated by Django 3.0.5 on 2020-05-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons_app', '0004_remove_persontype_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontype',
            name='definition',
            field=models.TextField(default='', max_length=500),
        ),
    ]
