# Generated by Django 3.0.5 on 2020-05-14 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons_app', '0005_auto_20200513_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['per_last_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='persontype',
            options={'ordering': ['type_name'], 'verbose_name': 'Person Type', 'verbose_name_plural': 'Person Types'},
        ),
    ]
