# Generated by Django 3.0.5 on 2020-05-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons_app', '0005_persontype_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='per_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pers_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='pers_tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
