# Generated by Django 3.0.5 on 2020-05-07 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persons_app', '0006_auto_20200502_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='per_date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='per_date_saved',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_website',
            field=models.URLField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='pers_tel',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
