# Generated by Django 3.0.5 on 2020-05-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons_app', '0007_auto_20200518_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='per_collection',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='per_date_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='per_date_saved',
            new_name='date_saved',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='per_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='per_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='per_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='per_tel',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='per_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='per_website',
            new_name='website',
        ),
    ]
