# Generated by Django 3.0.5 on 2020-05-08 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0022_auto_20200508_2344'),
        ('persons_app', '0008_auto_20200507_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='per_collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collections_app.Collection'),
            preserve_default=False,
        ),
    ]
