# Generated by Django 3.0.5 on 2020-05-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons_app', '0010_auto_20200509_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontype',
            name='definition',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
