# Generated by Django 3.0.5 on 2020-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons_app', '0011_auto_20200509_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='per_type',
            field=models.ManyToManyField(help_text='Choose all roles that are relevant. Create new role if there is not a fit.', related_name='Person', to='persons_app.PersonType'),
        ),
    ]
